config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resource :users

  resources :char_types do
    resources :char_attributes
  end

  resources :char_combats

  resource :render_async, :only => :show do
    member { get :render_me }
  end
end

app/models/char_attribute.rb
class CharAttribute < ActiveRecord::Base
  mount_uploader :icon, PictureUploader
  belongs_to :char_type

  validates :title, :presence => true,
                    :length => { :minimum => 3 }

  validates :value, :presence => true,
                    :numericality => { :greater_than_or_equal_to => 0 }

  scope :by_title, -> { order("title") }
end

app/models/char_combat.rb
class CharCombat < ActiveRecord::Base

  belongs_to :first_combatant, :class_name => CharType.to_s
  belongs_to :second_combatant, :class_name => CharType.to_s

  validates :first_combatant, :presence => true, :if => lambda { second_combatant == nil }
  validates :second_combatant, :presence => true, :if => lambda { first_combatant == nil }

  before_save :open_challenge, :combat

  def open_challenge
    self.challenge = (second == nil || first == nil)
    nil
  end

  def combat
    self.winner = first.attack_points > second.attack_points ? 
      first.id : second.id unless challenge
    nil
  end

  def first
    self.first_combatant
  end

  def second
    self.second_combatant
  end
end

app/models/char_type.rb
class CharType < ActiveRecord::Base
  mount_uploader :avatar, PictureUploader
  belongs_to :user
  has_many :char_attributes, :dependent => :destroy
  has_many :char_combats

  validates :title, :presence => true, :length => { :minimum => 3 }

  before_destroy :destroy_char_combat_history

  scope :by_title, -> { order("title") }

  def attack_points
    attr_sum = 0;

    self.char_attributes.each do |attribute|
      attr_sum += attribute.value
    end

    attr_sum / self.char_attributes.count + self.char_attributes.count
  end

  def destroy_char_combat_history
    CharCombat.delete_all
  end

  def combats
    CharCombat.where("first_combatant_id != ? OR second_combatant_id != ?",
                     self, self)
  end

  def challenges
    combats.where(:challenge => true)
  end

  def combat_history
    combats.where(:challenge => false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :char_types, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user! #:except => [:welcome:index]
end

app/controllers/char_attributes_controller.rb
class CharAttributesController < ApplicationController  
  respond_to :html, :js

  before_action :find_char_type, :only => [ :show, :edit, :destroy, 
                                            :new, :create, :update ]
  before_action :find_char_attribute, :only => [ :show, :edit, 
                                                 :destroy, :update ]
  
  def show
  end

  def new
    @char_attribute = @char_type.char_attributes.new
  end

  def edit
  end

  def create
    @char_attribute = @char_type.char_attributes.build(char_attributes_params)

    if @char_attribute.save
      redirect_to char_type_path(@char_type)
    else
      render 'new'
    end
  end

  def update
    if @char_attribute.update(char_attributes_params)
      redirect_to char_type_path(@char_type)
    else
      render 'edit'
    end
  end

  def destroy
    @char_attribute.destroy

    redirect_to char_types_path
  end

  private
  def char_attributes_params
    params.require(:char_attribute).permit(:title, :value, :icon)
  end

  def find_char_type
    @char_type = current_user.char_types.find_by_id(params[:char_type_id])
  end

  def find_char_attribute
    if @char_type
      @char_attribute = @char_type.char_attributes.find_by_id(params[:id])
    else
      nil
    end
  end
end

app/controllers/char_combats_controller.rb
class CharCombatsController < ApplicationController

  before_action :find_char_combat, :only => [ :show, :destroy, :update ]
  before_action :find_char_type, :only => [ :update ]

  def index
    @char_combats = combats(false)
    @combat_challenges = combats(true)
  end

  def create
    find_first_char
    find_second_char
    
    @char_combat = CharCombat.create!({ :first_combatant => @first_char,
                                        :second_combatant => @second_char })

    redirect_to char_combat_path(@char_combat)
  end

  def new
  end

  def show
    @char_combat = CharCombat.find_by_id(params[:id])
  end

  def destroy
    @char_combat.destroy

    redirect_to char_combats_path
  end

  def update
    
    if @char_combat.first_combatant
      @char_combat.second_combatant = @char_type
    else
      @char_combat.first_combatant = @char_type
    end

    @char_combat.save
    redirect_to char_combat_path(@char_combat)
  end

  private
  def find_first_char
    @first_char = current_user.char_types.find_by_id(params["char_combat"]["first_char"])
  end

  def find_second_char
    @second_char = current_user.char_types.find_by_id(params["char_combat"]["second_char"])
  end

  def find_char_type
    @char_type = current_user.char_types.find_by_id(params["char_type"])
  end

  def find_char_combat
    @char_combat = CharCombat.find_by_id(params[:id])
  end

  def combats(bool)
    CharCombat.where(:challenge => bool)
  end
end

app/controllers/char_types_controller.rb
class CharTypesController < ApplicationController
  before_action :find_char_type, :only => [ :show, :edit, :update, :destroy ]

  def index
    @char_types = current_user.char_types.by_title.page(params[:page]).per(4)
  end

  def show
    @char_attributes = @char_type.char_attributes.by_title.page(params[:page]).per(4)
  end

  def new
    @char_type = current_user.char_types.new
  end

  def edit
  end

  def create
    @char_type = current_user.char_types.new(char_type_params)

    if @char_type.save
      redirect_to char_type_path(@char_type)
    else
      render 'new'
    end
  end

  def update
    if @char_type.update(char_type_params)
      redirect_to char_type_path(@char_type)
    else
      render 'edit'
    end
  end

  def destroy
    @char_type.destroy

    redirect_to char_types_path
  end

  private
  def char_type_params
    params.require(:char_type).permit(:title, :avatar)
  end

  def find_char_type
    @char_type = current_user.char_types.find_by_id(params[:id])
  end
end

app/controllers/render_asyncs_controller.rb
class RenderAsyncsController < ApplicationController
  skip_before_filter :authenticate_user!

  def show
  end

  def render_me
    render :text => "Yo, I have jQuery."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/char_attributes_helper.rb
module CharAttributesHelper
end

app/helpers/char_types_helper.rb
module CharTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/char_attributes/_char_attribute.html.erb
<tr>
  <td>
    <%= char_attribute.title %>
  </td>

  <td>
    <%= char_attribute.value %>
  </td>
  <td><%= image_tag(char_attribute.icon, :width => 100, :height => 100) if char_attribute.icon.present? %></td>
  <td><%= link_to 'Show', char_type_char_attribute_path(:char_type_id => char_attribute.char_type.id,
                                                        :id => char_attribute.id) %>
  </td>
  <td><%= link_to 'Edit', edit_char_type_char_attribute_path(:char_type_id => char_attribute.char_type.id,
                                                             :id => char_attribute.id) %>
  </td>
  <td><%= link_to 'Destroy', char_type_char_attribute_path(:char_type_id => char_attribute.char_type.id,
                                                           :id => char_attribute.id), :method => :delete,
                                                           :data => { :confirm => "Are you sure?" },
                                                           :class => "destroy_link" %>
  </td>
</tr>

app/views/char_attributes/_form.html.erb
<%= form_for [@char_type, @char_type.char_attributes.build], html: { :class => "form-horizontal",
  :style => "display:inline;" } do |f| %>

  <% if @char_attribute.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@char_attribute.errors.count, "error") %> prohibited
        this character attribute from being saved:
      </h2>
      <ul>
        <% @char_attribute.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %><br>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div> 
  
  <div class="field form-group">
    <%= f.label :value, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :value, :min => 0, :max =>1000, :class => "form-control" %>  
    </div>
  </div>
 
  <div class="field form-group">
    <%= f.label :icon, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :icon, :accept => "image/png,image/gif,image/jpeg" %>
    </div>
  </div>
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/char_attributes/_form_show.html.erb
<%= form_for [@char_type, @char_attribute], html: { :class => "form-horizontal",
                                                    :style => "display:inline;" } do |f| %>

  <% if @char_attribute.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@char_attribute.errors.count, "error") %> prohibited
        this character attribute from being saved:
      </h2>
      <ul>
        <% @char_attribute.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div> 
  
  <div class="field form-group">
    <%= f.label :value, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :value, min:0, max:1000, :class => "form-control" %>  
    </div>
  </div>
 
  <div class="field form-group">
    <%= f.label :icon, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :icon, accept: "image/png,image/gif,image/jpeg" %>
    </div>
  </div>
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/char_attributes/edit.html.erb
<div class="col-sm-offset-1 col-sm-10">
  <h1>Edit "<%= @char_attribute.title %>" attribute</h1>
</div>

<%= render 'form_show' %>

<div class="col-sm-offset-1 col-sm-10">  
  <%= link_to 'Back', char_types_path %>
</div>

app/views/char_attributes/new.html.erb
<div class="col-sm-offset-1 col-sm-10">
  <h1>Add new attribute</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-1 col-sm-10">  
  <%= link_to 'Back', char_types_path %>
</div>

app/views/char_attributes/show.html.erb
<h1> Attribute "<%= @char_attribute.title %>"</h1>

<table class="table table-hover">
  <tr>
    <th>Attribute name</th>
    <th>Attribute value</th>
    <th>Attribute icon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%= render "char_attributes/char_attribute", :char_attribute => @char_attribute %>
</table>

<%= link_to 'Back', char_types_path %>

app/views/char_combats/_char_combats.html.erb
<table class="table table-hover">
  <tr class="info">
    <th>Fight number</th>
    <th>Winner</th>
    <th>Loser</th>
    <th></th>
    <th></th>
  </tr>
  <% @char_combats.each do |char_combat| %>
    <tr>
      <td>Fight <%= char_combat.id %></td>
      <td><%= render "char_combats/winner", :char_combat => char_combat %></td>
      <td><%= render "char_combats/loser", :char_combat => char_combat %></td>
      <td><%= link_to "Show", char_combat_path(char_combat) %></td>
      <td><%= link_to "Destroy", char_combat_path(char_combat), :method => :delete,
              :data => { :confirm => 'Are you sure?' } %>
    </tr>
  <% end %>
</table>

app/views/char_combats/_combat_challenges.html.erb
<table class="table table-hover">
  <tr class="info">
    <th>Fight number</th>
    <th>First combatant</th>
    <th>Second combatant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% combat_challenges.each do |char_combat| %>
    <tr>
      <td>Challenge <%= char_combat.id %></td>
      <td><%= render "char_combats/first", :char_combat => char_combat %></td>
      <td><%= render "char_combats/second", :char_combat => char_combat %></td>
          <% if @char_type %>
      <td><%= link_to "Join", char_combat_path(char_combat, :char_type => @char_type),
                      :method => :patch %></td>
          <% end %>
      <td><%= link_to "Show", char_combat_path(char_combat) %></td>
      <td><%= link_to "Destroy", char_combat_path(char_combat), :method => :delete,
              :data => { :confirm => 'Are you sure?' } %>
    </tr>
  <% end %>
</table>

app/views/char_combats/_first.html.erb
<% if char_combat.first_combatant == nil %>
  <f></f>
<% else %>
  <%= char_combat.first_combatant.title %>
<% end %>

app/views/char_combats/_loser.html.erb
<% if char_combat.winner == char_combat.second_combatant.id %>
  <%= char_combat.first_combatant.title %>
<% else %>
  <%= char_combat.second_combatant.title %>
<% end %>

app/views/char_combats/_second.html.erb
<% if char_combat.second_combatant == nil %>
  <f></f>
<% else %>
  <%= char_combat.second_combatant.title %>
<% end %>

app/views/char_combats/_winner.html.erb
<% if char_combat.winner == char_combat.first_combatant.id %>
  <%= char_combat.first_combatant.title %>
<% else %>
  <%= char_combat.second_combatant.title %>
<% end %>

app/views/char_combats/index.html.erb
<h1>Borbe bikova</h1>

<%= link_to "New combat", new_char_combat_path %>

<%= render "char_combats" %>

<%= render "combat_challenges", :combat_challenges => @combat_challenges %>

app/views/char_combats/new.html.erb
<div class="col-sm-offset-1 col-sm-10">  
  <h1>Character combats</h1>
</div>

<%= form_for :char_combat, :url => char_combats_path, :html => { :class => "form-horizontal" } do |form| %>
  <div class="field form-group">
    <%= form.label :first_char, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.collection_select("first_char", 
                                 current_user.char_types, :id, :title, { include_blank: true }) %>
    </div>
  </div>
  <div class="field form-group">
    <%= form.label :second_char, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.collection_select("second_char",
                                 current_user.char_types, :id, :title, { include_blank: true }) %>
    </div>
  </div>
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">  
      <%= form.submit "Fight" %>
    </div>
  </div>
<% end %>

app/views/char_combats/show.html.erb
<div class="col-sm-offset-1 col-sm-10">
  <% if @char_combat.challenge %>
    <h1>Open challenge:</h1>

    <strong>First combatant:</strong>
    <%= render "first", :char_combat => @char_combat %>
    <br>
    <strong>Second combatant:</strong>
    <%= render "second", :char_combat => @char_combat %>
  <% else %>
    <h1>And the winner is:</h1>

    <%= render 'winner', :char_combat => @char_combat %>

    <h1>Loser is:</h1>

    <%= render 'loser', :char_combat => @char_combat %>
  <% end %>
</div>

app/views/char_types/_all_attributes_table.html.erb
<table class="table table-hover">
  <tr class="info">
    <th>Attribute name</th>
    <th>Attribute value</th>
    <th>Attribute icon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%= paginate @char_attributes %>

  <% @char_attributes.each do |char_attribute| %>
    <%= render "char_attributes/char_attribute", :char_attribute => char_attribute %>
  <% end %>

  <tr>
    <th><%= link_to 'Add more attributes', new_char_type_char_attribute_path(@char_type)%></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>

app/views/char_types/_char_type.html.erb
<td><%= char_type.title %></td>
<td><%= image_tag(char_type.avatar, :width => 100, :height => 100) if char_type.avatar.present? %></td>
<td><%= link_to 'Show', char_type_path(char_type) %></td>
<td><%= link_to 'Edit', edit_char_type_path(char_type) %></td>
<td><%= link_to 'Destroy', char_type_path(char_type), :method => :delete,
              data: { confirm: 'Are you sure?' } %></td>
<td>

app/views/char_types/_form.html.erb
<%= form_for :char_type, :url => char_types_path, 
                         :html => { :class => "form-horizontal", :multipart => true } do |f| %>
  <% if @char_type.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@char_type.errors.count, "error") %> prohibited
        this character type from being saved:
      </p>
      <ul>
        <% @char_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div> 
  
  <div class="field form-group">
    <%= f.label :avatar, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :avatar %>
    </div>
  </div>
  
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit character type" %>
    </div>
  </div>
<% end %>

app/views/char_types/edit.html.erb
<div class="col-sm-offset-1 col-sm-10">
  <h1>Edit "<%= @char_type.title %>" type</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-1 col-sm-10">  
  <%= link_to 'Back', char_types_path %>
</div>

app/views/char_types/index.html.erb
<h1>Listing character types</h1>
 
<%= link_to new_char_type_path, :class => "btn btn-success" do %>
  <i class="glyphicon glyphicon-plus"></i> New character type
<% end %>

<p></p>
<%= paginate @char_types %>
<% if current_user.char_types.present? %>
<table class="table table-hover">
  <tr class="info">
    <th>Title</th>
    <th>Avatar</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Attributes</th>
  </tr>
 
  <% @char_types.each do |type| %>
    <tr>
      <%= render type %>
        <% if type.char_attributes.present? %>
          <table class="table table-hover">
            <tr class="info">
              <th>Attribute name</th>
              <th>Attribute value</th>
              <th>Attribute icon</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            
              <%= render type.char_attributes.order(:title) %>
              
            <tr>
              <th><%= link_to 'Add more attributes', new_char_type_char_attribute_path(type)%></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </table>
        <% else %>
          <p>This character type has no attributes! 
          <%= link_to 'Add some', new_char_type_char_attribute_path(type) %>.</p>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<% else %>
  <p>You haven't created any characters yet! <%= link_to 'Create some', new_char_type_path %>.</p>
<% end %>

app/views/char_types/index.js.erb
$("#new-char-type-modal").html("<%= escape_javascript(render 'char_attributes/new') %>")
$("#new-char-type-modal").modal("show")

app/views/char_types/new.html.erb
<div class="col-sm-offset-1 col-sm-10">  
  <h1>New character type</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-1 col-sm-10">  
  <%= link_to 'Back', char_types_path %>
</div>

app/views/char_types/show.html.erb
<div class="col-sm-offset-0 col-sm-10">
  <h1>Character "<%= @char_type.title %>"</h1>
</div>
<div class="col-sm-offset-0 col-sm-10">
<p>
  <strong>Title:</strong> <%= @char_type.title %>
</p>

<p>
  <strong>Avatar:</strong> <%= image_tag(@char_type.avatar, :width => 100, :height => 100) if @char_type.avatar? %>
</p>

<strong>Attributes:</strong>
</div>
<% if @char_type.char_attributes.present? %>
  <%= render 'all_attributes_table' %>
<% else %>
  <div class="col-sm-offset-0 col-sm-10">
    This character type has no attributes! <%= link_to 'Add some', new_char_type_char_attribute_path(@char_type) %>.
  </div>
<% end %>

<% @char_combats = @char_type.combat_history %>

<strong>Previous fights:</strong>
<%= render "char_combats/char_combats" %>

<strong>Open challenges:</strong>
<%= render "char_combats/combat_challenges", :combat_challenges => @char_type.challenges %>

<div class="col-sm-offset-0 col-sm-10">
  <%= link_to 'Back', char_types_path %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">RPG App</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RPG App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <style type="text/css">
      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      img {
        display: block;
        max-width:600px;
        max-height:300px;
        width: auto;
        height: auto;
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
  </style>
</head>
<body>
  <div id="wrap">

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><i>RPG App</i></a>
        </div>

        <ul class="nav navbar-nav">
        <li class="active"><%= link_to "All characters", char_types_path %></li>
        <li><%= link_to "New character", new_char_type_path %></li>
        <li><%= link_to "All combats", char_combats_path %></li>
        <li><%= link_to "NEW WOMBAT", new_char_combat_path %></li>
        <% if user_signed_in? %>
          <li class="pull-right"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <!-- Added for Devise -->
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </div>


  <div id="footer">
    <div class="container">
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    </div>
  </div>

  <%= content_for :render_async %>
</body>
</html>

app/views/render_asyncs/show.html.erb
<h1>render_async test</h1>

<%= render_async render_me_render_async_path %>

<p>
  jQuery: <script>document.write(window.jQuery)</script>
</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<html>
  <body>
    <div id="main-container" class="container">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <h1>Hi there</h1>
        </div>
        <div id="content" class="col-xs-9">
          <p>This is your basic RPG characters editor</p>
          <p>You can add your new characters and their attributes!</p>
          <%= link_to 'See what you made so far', controller: 'char_types' %>
        </div>
      </div>
    </div>
  </body>
</html>